name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: pip install .
      - run: pip install numpy
      - run: pip install pytest
      - run: pip install scipy
      - run: pytest -v
